## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [8]:
from sklearn.model_selection import train_test_split
import numpy as np
one_index = np.where(y==1)[0]
zero_index = np.where(y==0)[0]

In [9]:
X_one_train, X_one_test, y_one_train, y_one_test = train_test_split(X[one_index], y[one_index], test_size=10)
X_zero_train, X_zero_test, y_zero_train, y_zero_test = train_test_split(X[zero_index], y[zero_index], test_size=10)
X_one_test

array([[ 70,  71,  72,  73,  74],
       [ 20,  21,  22,  23,  24],
       [ 45,  46,  47,  48,  49],
       [ 15,  16,  17,  18,  19],
       [185, 186, 187, 188, 189],
       [ 95,  96,  97,  98,  99],
       [105, 106, 107, 108, 109],
       [120, 121, 122, 123, 124],
       [ 75,  76,  77,  78,  79],
       [190, 191, 192, 193, 194]])

In [10]:
x_train=np.concatenate((X_one_train, X_zero_train), axis=None)
y_test=np.concatenate((y_one_test, y_zero_test), axis=None)

In [11]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])